"""
Django settings for danielmherman project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path

from csp.constants import NONCE, NONE, SELF
from django.core.exceptions import ImproperlyConfigured

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ---------- ENVIRONMENT ----------
# Fail-closed (S1-01/ECC-46): no permissive default — every runtime must say
# what it is. 'collectstatic' exists for the image build, which needs settings
# but neither secrets nor a database.
_ALLOWED_ENVIRONMENTS = ('production', 'development', 'collectstatic')
ENVIRONMENT = os.environ.get('ENVIRONMENT', '').strip()
if ENVIRONMENT not in _ALLOWED_ENVIRONMENTS:
    raise ImproperlyConfigured(
        "ENVIRONMENT must be set to one of: production, development, "
        f"collectstatic (got {ENVIRONMENT!r}). See .env.example."
    )
IS_PRODUCTION = ENVIRONMENT == 'production'

# Fail fast on missing prod config (S9-01) — these otherwise surface as opaque
# runtime failures (empty /cloudsql/ host, 400s, 403s on every POST).
if IS_PRODUCTION:
    _missing = [
        name for name in (
            'GOOGLE_CLOUD_PROJECT',
            'CLOUD_SQL_CONNECTION_NAME',
            'ALLOWED_HOSTS',
            'CSRF_TRUSTED_ORIGINS',
            'GS_BUCKET_NAME',
            'DEMO_AGENT_URL',
        ) if not os.environ.get(name, '').strip()
    ]
    if _missing:
        raise ImproperlyConfigured(
            'Missing required production env vars: ' + ', '.join(_missing)
        )

# ---------- SECRET KEY ----------
if IS_PRODUCTION:
    from google.cloud import secretmanager

    client = secretmanager.SecretManagerServiceClient()
    PROJECT_ID = os.environ.get('GOOGLE_CLOUD_PROJECT')

    def get_secret(secret_id):
        name = f"projects/{PROJECT_ID}/secrets/{secret_id}/versions/latest"
        response = client.access_secret_version(request={"name": name})
        return response.payload.data.decode("UTF-8")

    SECRET_KEY = get_secret('django-secret-key')
else:
    # Local development only. Override via DJANGO_SECRET_KEY if you need a
    # stable key across restarts. The 'django-insecure-' prefix is Django's
    # own convention and is flagged by `manage.py check --deploy`.
    SECRET_KEY = os.environ.get(
        'DJANGO_SECRET_KEY',
        'django-insecure-local-dev-only-never-use-in-production',
    )

# ---------- DEBUG ----------
DEBUG = not IS_PRODUCTION

# ---------- ALLOWED HOSTS ----------
# Strip + drop empty entries (S9-03): "a.com, b.com" must not yield ' b.com'.
def _env_list(name, default=''):
    return [p.strip() for p in os.environ.get(name, default).split(',') if p.strip()]

ALLOWED_HOSTS = _env_list('ALLOWED_HOSTS', 'localhost,127.0.0.1')

# ---------- CSRF ----------
CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS', 'http://localhost:8000')

# ---------- CLINICAL COPILOT DEMO ----------
# The private Cloud Run agent. Must be the service URL with no path: it doubles
# as the ID token audience, and a mismatched audience fails with a 401 that
# looks exactly like a missing IAM binding. No committed default (S1-10):
# required in production, and agent_client raises a clear error when unset.
DEMO_AGENT_URL = os.environ.get('DEMO_AGENT_URL', '')
# Generous on purpose: a cold agent instance and a cold MCP instance can land on
# the same request, and both scale to zero.
DEMO_AGENT_TIMEOUT = int(os.environ.get('DEMO_AGENT_TIMEOUT', '120'))
DEMO_DAILY_LIMIT = int(os.environ.get('DEMO_DAILY_LIMIT', '10'))
# Refunds for failures that DID incur model spend (agent timeouts, tool
# errors) are capped per user per day, or a request engineered to always fail
# downstream turns the refund loop into unmetered Gemini spend (S1-09).
# Provably-zero-spend failures (connection refused before dispatch) refund
# without touching the cap.
DEMO_DAILY_REFUND_CAP = int(os.environ.get('DEMO_DAILY_REFUND_CAP', '3'))
# Agent calls block a sync-view worker thread for up to DEMO_AGENT_TIMEOUT.
# Bounding them per instance keeps slow agent calls from exhausting the
# thread pool and stalling the whole public site (S1-15).
DEMO_AGENT_MAX_CONCURRENCY = int(os.environ.get('DEMO_AGENT_MAX_CONCURRENCY', '4'))

# Dev scaffolding only (S1-02): captured payloads used while building the UI.
# Off by default and never allowed in production — the live site always calls
# the live agent.
DEMO_FIXTURE_MODE = os.environ.get(
    'DEMO_FIXTURE_MODE', 'false'
).strip().lower() in ('1', 'true', 'yes', 'on')
if IS_PRODUCTION and DEMO_FIXTURE_MODE:
    raise ImproperlyConfigured(
        'DEMO_FIXTURE_MODE is dev scaffolding and must not be enabled in production.'
    )

LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'demo:console'
LOGOUT_REDIRECT_URL = 'home'


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'content', # added app
    'demo',    # clinical copilot demo: patient cohort + quota
    'django_ckeditor_5',
    'storages',   # Cloud Storage media backend
    'channels',   # Django Channels (WebSocket/ASGI support)
]

# CKEditor 5 Configuration
# Uploads use Django's default storage (STORAGES["default"]) — GCS in
# production, local /media/ in development. Do NOT pin CKEDITOR_5_FILE_STORAGE
# to FileSystemStorage here: in production that writes images to the ephemeral
# container disk while MEDIA_URL points at the GCS bucket, so uploaded images
# 404.
CKEDITOR_5_UPLOAD_FILE_TYPES = ['jpeg', 'jpg', 'png', 'gif', 'webp']
# Only staff may hit the upload route (S1-13) — it is mounted publicly at
# /ckeditor5/ and would otherwise accept uploads from any authenticated user.
CKEDITOR_5_FILE_UPLOAD_PERMISSION = 'staff'

CKEDITOR_5_CONFIGS = {
    'default': {
        'toolbar': {
            'items': [
                'heading', '|',
                'bold', 'italic', 'underline', 'strikethrough', 'superscript', 'subscript', '|',
                'fontColor', 'fontBackgroundColor', '|',
                'bulletedList', 'numberedList', '|',
                'undo', 'redo',
                '-',  # Line break - second row
                'fontSize', 'fontFamily', '|',
                'link', 'insertImage', 'mediaEmbed', 'blockQuote', 'codeBlock', 'insertTable', '|',
                'horizontalLine', 'sourceEditing',
            ],
            'shouldNotGroupWhenFull': True,
        },
        'heading': {
            'options': [
                {'model': 'paragraph', 'title': 'Paragraph', 'class': 'ck-heading_paragraph'},
                {'model': 'heading2', 'view': 'h2', 'title': 'Heading 2', 'class': 'ck-heading_heading2'},
                {'model': 'heading3', 'view': 'h3', 'title': 'Heading 3', 'class': 'ck-heading_heading3'},
                {'model': 'heading4', 'view': 'h4', 'title': 'Heading 4', 'class': 'ck-heading_heading4'},
            ]
        },
        'fontFamily': {
            'options': [
                'default',
                'Georgia, serif',
                'Arial, sans-serif',
                'Courier New, monospace',
                'Inter, sans-serif',
            ],
        },
        'fontSize': {
            'options': [
                'tiny', 'small', 'default', 'big', 'huge',
            ],
        },
        'codeBlock': {
            'languages': [
                {'language': 'mermaid', 'label': 'Mermaid'},
                {'language': 'plaintext', 'label': 'Plain text'},
                {'language': 'python', 'label': 'Python'},
                {'language': 'javascript', 'label': 'JavaScript'},
                {'language': 'html', 'label': 'HTML'},
                {'language': 'css', 'label': 'CSS'},
                {'language': 'sql', 'label': 'SQL'},
                {'language': 'bash', 'label': 'Bash'},
            ],
        },
        'mediaEmbed': {
            'previewsInData': True,
        },
        'image': {
            'toolbar': [
                'imageTextAlternative', 'imageStyle:inline', 'imageStyle:block', 'imageStyle:side',
            ],
        },
        'table': {
            'contentToolbar': ['tableColumn', 'tableRow', 'mergeTableCells'],
        },
        # Concrete allowlist (S1-13), not the previous allow-everything
        # /.*/ — this is editor-side convenience config only; the actual
        # security boundary is the server-side nh3 sanitizer applied at
        # render (content_extras.sanitize, S6-01). Keep the two lists in sync.
        'htmlSupport': {
            'allow': [
                {'name': name, 'attributes': True, 'classes': True, 'styles': True}
                for name in (
                    'p', 'br', 'hr', 'blockquote',
                    'h2', 'h3', 'h4', 'h5', 'h6',
                    'ul', 'ol', 'li',
                    'strong', 'em', 'u', 's', 'sup', 'sub', 'span', 'mark',
                    'a', 'img', 'figure', 'figcaption', 'oembed', 'iframe',
                    'pre', 'code',
                    'table', 'thead', 'tbody', 'tr', 'td', 'th',
                )
            ]
        },
    },
}


MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'danielmherman.csp_middleware.PathExemptCSPMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# ---------- CONTENT SECURITY POLICY (S6-10 / S7-03) ----------
# The backstop for a site that renders sanitized rich HTML plus CDN scripts:
# a missed sink can no longer load foreign script. Inline scripts use nonces
# ({{ request.csp_nonce }}); style allows inline because CKEditor content and
# mermaid/AOS legitimately emit style attributes. /admin/ and /ckeditor5/ are
# exempted in the middleware subclass — the editor relies on inline script,
# and those routes are staff-only.
CONTENT_SECURITY_POLICY = {
    'DIRECTIVES': {
        'default-src': [SELF],
        'script-src': [SELF, NONCE,
                       'https://cdn.jsdelivr.net', 'https://cdnjs.cloudflare.com'],
        'style-src': [SELF, "'unsafe-inline'",
                      'https://cdn.jsdelivr.net', 'https://cdnjs.cloudflare.com',
                      'https://fonts.googleapis.com'],
        'font-src': [SELF, 'data:', 'https://fonts.gstatic.com',
                     'https://cdnjs.cloudflare.com', 'https://cdn.jsdelivr.net'],
        'img-src': [SELF, 'data:', 'https://storage.googleapis.com',
                    'https://static.djangoproject.com'],
        'connect-src': [SELF],
        'frame-src': ['https://www.youtube.com', 'https://www.youtube-nocookie.com'],
        'object-src': [NONE],
        'base-uri': [SELF],
        'form-action': [SELF],
        'frame-ancestors': [SELF],
    },
}

ROOT_URLCONF = 'danielmherman.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'danielmherman.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

if IS_PRODUCTION:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'NAME': 'danielmherman',
            'USER': 'djangouser',
            'PASSWORD': get_secret('db-password'),
            'HOST': '/cloudsql/' + os.environ.get('CLOUD_SQL_CONNECTION_NAME', ''),
            'PORT': '5432',
        }
    }
else:
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': BASE_DIR / 'db.sqlite3',
        }
    }


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

# ---------- STATIC FILES ----------
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [BASE_DIR / 'static']

STORAGES = {
    "default": {
        "BACKEND": "django.core.files.storage.FileSystemStorage",
    },
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# ---------- MEDIA FILES ----------
if IS_PRODUCTION:
    STORAGES["default"] = {
        "BACKEND": "storages.backends.gcloud.GoogleCloudStorage",
    }
    GS_BUCKET_NAME = os.environ['GS_BUCKET_NAME']  # required, validated at boot
    # Portfolio media (article/project images) is intentionally world-readable
    # — it renders on public pages. Uploads are staff-only (S1-13); nothing
    # sensitive is ever written to this bucket.
    GS_DEFAULT_ACL = 'publicRead'
    MEDIA_URL = f'https://storage.googleapis.com/{GS_BUCKET_NAME}/'
else:
    MEDIA_URL = '/media/'
    MEDIA_ROOT = BASE_DIR / 'media'

# ---------- SECURITY (production only) ----------
if IS_PRODUCTION:
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True

# ---------- ASGI / CHANNELS ----------
ASGI_APPLICATION = 'danielmherman.asgi.application'

# Redis is only required for cross-process WebSocket broadcast (group_send).
# Without REDIS_HOST set, the in-memory layer is used — correct for
# request/response and single-connection streaming workloads.
REDIS_HOST = os.environ.get('REDIS_HOST')

if REDIS_HOST:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels_redis.core.RedisChannelLayer',
            'CONFIG': {
                'hosts': [(REDIS_HOST, 6379)],
            },
        },
    }
else:
    CHANNEL_LAYERS = {
        'default': {
            'BACKEND': 'channels.layers.InMemoryChannelLayer',
        },
    }

# ---------- LOGGING ----------
# With DEBUG=False, Django routes unhandled exceptions to the 'django.request'
# logger, whose only default handler is 'mail_admins'. With no email backend
# configured that means production tracebacks are silently discarded — a 500 in
# Cloud Run shows the status line and nothing else.
#
# Sending them to stdout is enough: Cloud Run captures stdout/stderr into Cloud
# Logging automatically, so no logging agent or client library is needed.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'loggers': {
        # Unhandled view exceptions and 4xx/5xx responses.
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Startup/runtime errors that are not tied to a request.
        'django': {
            'handlers': ['console'],
            'level': 'INFO' if IS_PRODUCTION else 'WARNING',
            'propagate': False,
        },
        # Application code: use logging.getLogger(__name__) in views/services.
        'content': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'WARNING',
    },
}