# Generated by Django 6.0 on 2026-07-30 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DemoPatient',
            fields=[
                ('hadm_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('display_name', models.CharField(db_index=True, help_text='Synthetic. Never a real patient name.', max_length=100)),
                ('age', models.PositiveSmallIntegerField()),
                ('sex', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('summary', models.CharField(help_text='Clinical descriptor. Must not hint at the predicted outcome.', max_length=255)),
                ('split_name', models.CharField(help_text='Source split. Demo patients must not be rows the model trained on.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'demo patient',
                'verbose_name_plural': 'demo patients',
                'ordering': ['display_name'],
            },
        ),
    ]
