# Generated by Django 6.0 on 2026-07-30 22:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoQuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_limit', models.PositiveSmallIntegerField(default=10, help_text='Requests permitted per calendar day.')),
                ('used', models.PositiveSmallIntegerField(default=0)),
                ('period_start', models.DateField(default=django.utils.timezone.localdate)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='demo_quota', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'demo quota',
                'verbose_name_plural': 'demo quotas',
            },
        ),
    ]
