# Generated by Django 6.0.8 on 2026-09-18 19:01

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0003_demoquota_refunds'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_turn_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('turn_count', models.PositiveSmallIntegerField(default=0, help_text='User turns spent so far; the ceiling is a hard limit.')),
                ('patient', models.ForeignKey(help_text='Pinned at creation. Changing it is refused, not discouraged.', on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to='demo.demopatient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'conversation',
                'verbose_name_plural': 'conversations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Turn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordinal', models.PositiveSmallIntegerField()),
                ('role', models.CharField(choices=[('user', 'User'), ('agent', 'Agent')], max_length=8)),
                ('question', models.TextField(blank=True, default='')),
                ('answer', models.TextField(blank=True, default='')),
                ('model', models.CharField(blank=True, default='', max_length=64)),
                ('code_revision', models.CharField(blank=True, default='', max_length=64)),
                ('citations', models.JSONField(blank=True, default=list)),
                ('tool_calls', models.JSONField(blank=True, default=list)),
                ('error', models.CharField(blank=True, default='', max_length=200)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='turns', to='demo.conversation')),
            ],
            options={
                'verbose_name': 'turn',
                'verbose_name_plural': 'turns',
                'ordering': ['ordinal'],
                'constraints': [models.UniqueConstraint(fields=('conversation', 'ordinal'), name='unique_turn_ordinal_per_conversation')],
            },
        ),
    ]
