# Generated by Django 6.0.8 on 2026-09-18 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_conversation_turn'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='guardrail_flags',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
