# Generated by Django 6.0.8 on 2026-09-19 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0005_turn_guardrail_flags'),
    ]

    operations = [
        migrations.AddField(
            model_name='turn',
            name='langfuse_trace_id',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
