# Generated by Django 6.0 on 2026-01-11 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_article'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='projects/')),
                ('demo_link', models.URLField(blank=True, help_text='Link to hosted UI')),
                ('github_link', models.URLField(blank=True, help_text='Link to source code')),
                ('technologies', models.CharField(help_text='e.g. Python, TensorFlow, GCO ', max_length=200)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(choices=[('tech', 'Tech'), ('music', 'Music'), ('enlightenment', 'Enlightenment'), ('resume', 'Resume'), ('projects', 'Projects'), ('contact', 'Contact')], max_length=50, unique=True),
        ),
    ]
