# Generated by Django 6.0 on 2026-01-12 19:42

# Originally ckeditor.fields.RichTextField (django-ckeditor, removed 2026-08-31
# per S9-05); rewritten as its base TextField — same DB type, no schema change.
# Superseded by 0005 anyway.
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_project_delete_service_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='content',
            field=models.TextField(),
        ),
    ]
