# Generated by Django 6.0 on 2026-08-13 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0008_alter_article_content_alter_project_content'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='drilldown',
            field=models.BooleanField(default=False, help_text='Split content into section cards + per-section pages'),
        ),
    ]
