# Generated by hand — sets the ECC project to drill-down mode so the deployed
# site matches the approved "current config" (landing cards + per-section pages).
from django.db import migrations

ECC_SLUG = "enterprise-clinical-copilot"


def enable_drilldown(apps, schema_editor):
    Project = apps.get_model("content", "Project")
    Project.objects.filter(slug=ECC_SLUG).update(drilldown=True)


def disable_drilldown(apps, schema_editor):
    Project = apps.get_model("content", "Project")
    Project.objects.filter(slug=ECC_SLUG).update(drilldown=False)


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0009_project_drilldown"),
    ]

    operations = [
        migrations.RunPython(enable_drilldown, disable_drilldown),
    ]
